version: '3.8'

services:
  whale-sentinel-opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: whale-sentinel-opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: https://whale-sentinel-opensearch-database:9200
    ports:
      - "5601:5601"
    networks:
      - whale-sentinel-controller-network
    depends_on:
      - whale-sentinel-opensearch-database

  whale-sentinel-opensearch-database:
    image: opensearchproject/opensearch:latest
    container_name: whale-sentinel-opensearch-database
    environment:
      discovery.type: single-node
      plugins.security.disabled: "false" # Disable security for local development
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: your-opensearch-password
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - whale-sentinel-controller-network

networks:
  whale-sentinel-controller-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ws-control-nw
    ipam:
      config:
        - subnet: "172.24.0.0/16"